import type { DatasetInfo, LoraConfig, ModelArch, TrainConfig } from '../types'
import { totalSteps } from './lora'

export interface CodegenInput {
  model: ModelArch
  dataset: DatasetInfo
  lora: LoraConfig
  train: TrainConfig
  runName: string
}

const py = (b: boolean) => (b ? 'True' : 'False')

export function generateRequirements(train: TrainConfig): string {
  const lines = [
    'torch>=2.3.0',
    'transformers>=4.44.0',
    'datasets>=2.20.0',
    'peft>=0.12.0',
    'trl>=0.9.6',
    'accelerate>=0.33.0',
  ]
  if (train.quant !== 'none') lines.push('bitsandbytes>=0.43.1')
  if (train.wandb) lines.push('wandb>=0.17.0')
  return lines.join('\n') + '\n'
}

export function generateTrainPy(input: CodegenInput): string {
  const { model, dataset, lora, train, runName } = input
  const steps = totalSteps(dataset.rows, train)
  const warmup = Math.round(steps * train.warmupRatio)
  const targets = lora.targets.map((t) => `"${t}"`).join(', ')
  const quantBlock =
    train.quant === 'none'
      ? `bnb_config = None`
      : `bnb_config = BitsAndBytesConfig(
    load_in_4bit=${py(train.quant === '4bit')},
    load_in_8bit=${py(train.quant === '8bit')},
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
)`

  return `#!/usr/bin/env python
"""
${runName} — generated by Forge (LLM Fine-Tuning Laboratory).
Fine-tunes ${model.name} on ${dataset.name} with ${
    train.quant === 'none' ? 'LoRA' : 'QLoRA (' + train.quant + ')'
} via PEFT + TRL.

Run:  pip install -r requirements.txt  &&  python train.py
"""
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig, prepare_model_for_kbit_training
from trl import SFTTrainer

MODEL_ID = "${model.hf}"
DATASET_ID = "${dataset.hf}"
OUTPUT_DIR = "outputs/${runName}"

# ── Quantization (QLoRA loads the frozen base in low precision) ──────────────
${quantBlock}

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    torch_dtype=torch.bfloat16,
    device_map="auto",
)
model.config.use_cache = False
${train.quant === 'none' ? '' : 'model = prepare_model_for_kbit_training(model)\n'}
# ── LoRA adapter ─────────────────────────────────────────────────────────────
peft_config = LoraConfig(
    r=${lora.r},
    lora_alpha=${lora.alpha},
    lora_dropout=${lora.dropout},
    target_modules=[${targets}],
    bias="none",
    task_type="CAUSAL_LM",
)

# ── Data: format each row into a single supervised prompt ────────────────────
dataset = load_dataset(DATASET_ID, split="train")

def format_example(ex):
    instruction = ex.get("instruction") or ex.get("prompt") or ""
    context = ex.get("input") or ex.get("context") or ""
    response = ex.get("output") or ex.get("response") or ex.get("completion") or ""
    if context:
        text = (
            "### Instruction:\\n" + instruction + "\\n\\n"
            "### Input:\\n" + context + "\\n\\n"
            "### Response:\\n" + response
        )
    else:
        text = "### Instruction:\\n" + instruction + "\\n\\n### Response:\\n" + response
    return {"text": text + tokenizer.eos_token}

dataset = dataset.map(format_example, remove_columns=dataset.column_names)

# ── Training ─────────────────────────────────────────────────────────────────
args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=${train.epochs},
    per_device_train_batch_size=${train.batchSize},
    gradient_accumulation_steps=${train.gradAccum},
    learning_rate=${train.learningRate},
    lr_scheduler_type="${train.scheduler}",
    warmup_steps=${warmup},
    logging_steps=${train.loggingSteps},
    save_steps=${train.saveSteps},
    bf16=True,
    gradient_checkpointing=True,
    optim="${train.quant === 'none' ? 'adamw_torch' : 'paged_adamw_8bit'}",
    seed=${train.seed},
    report_to=${train.wandb ? '"wandb"' : '"none"'},
    run_name="${runName}",
)

trainer = SFTTrainer(
    model=model,
    args=args,
    train_dataset=dataset,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=${train.maxSeqLen},
    tokenizer=tokenizer,
)

trainer.train()                       # ~${steps} optimizer steps
trainer.save_model(OUTPUT_DIR)        # saves the LoRA adapter
print("Done →", OUTPUT_DIR)
`
}

export function generateQuantizeScript(
  method: 'gguf' | 'awq' | 'gptq',
  bits: number,
  model: ModelArch,
  runName: string,
): string {
  const merged = `outputs/${runName}-merged`
  if (method === 'gguf') {
    return `#!/usr/bin/env bash
# Merge the LoRA adapter, then convert to GGUF (${bits}-bit) for llama.cpp / Ollama.
python -c "
from peft import AutoPeftModelForCausalLM
from transformers import AutoTokenizer
m = AutoPeftModelForCausalLM.from_pretrained('outputs/${runName}')
m = m.merge_and_unload()
m.save_pretrained('${merged}')
AutoTokenizer.from_pretrained('${model.hf}').save_pretrained('${merged}')
"
git clone https://github.com/ggerganov/llama.cpp && cd llama.cpp && make -j
python convert_hf_to_gguf.py ../${merged} --outfile ${runName}-f16.gguf --outtype f16
./llama-quantize ${runName}-f16.gguf ${runName}-q${bits}.gguf Q${bits}_K_M
`
  }
  if (method === 'awq') {
    return `#!/usr/bin/env python
# Activation-aware Weight Quantization (${bits}-bit) via AutoAWQ.
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer

model_path = "outputs/${runName}-merged"
quant_path = "outputs/${runName}-awq"
quant_config = {"w_bit": ${bits}, "q_group_size": 128, "zero_point": True, "version": "GEMM"}

model = AutoAWQForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)
model.quantize(tokenizer, quant_config=quant_config)
model.save_quantized(quant_path)
tokenizer.save_pretrained(quant_path)
`
  }
  return `#!/usr/bin/env python
# GPTQ ${bits}-bit quantization via AutoGPTQ.
from transformers import AutoTokenizer
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig

model_path = "outputs/${runName}-merged"
quant_path = "outputs/${runName}-gptq"
tokenizer = AutoTokenizer.from_pretrained(model_path)
examples = [tokenizer("Fine-tuning large language models is")]

quantize_config = BaseQuantizeConfig(bits=${bits}, group_size=128, desc_act=False)
model = AutoGPTQForCausalLM.from_pretrained(model_path, quantize_config)
model.quantize(examples)
model.save_quantized(quant_path)
`
}

export function generateNotebook(input: CodegenInput): string {
  const trainPy = generateTrainPy(input)
  const reqs = generateRequirements(input.train)
  const cell = (source: string, type: 'code' | 'markdown') => ({
    cell_type: type,
    metadata: {},
    ...(type === 'code' ? { execution_count: null, outputs: [] } : {}),
    source: source.split('\n').map((l, i, a) => (i === a.length - 1 ? l : l + '\n')),
  })
  const nb = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      colab: { provenance: [], gpuType: 'T4' },
      accelerator: 'GPU',
      kernelspec: { name: 'python3', display_name: 'Python 3' },
    },
    cells: [
      cell(
        `# 🔥 ${input.runName}\n` +
          `Fine-tune **${input.model.name}** on **${input.dataset.name}** with ` +
          `${input.train.quant === 'none' ? 'LoRA' : 'QLoRA'}.\n\n` +
          `_Generated by Forge — LLM Fine-Tuning Laboratory._`,
        'markdown',
      ),
      cell(`!pip install -q ${generateRequirements(input.train).trim().split('\n').join(' ')}`, 'code'),
      cell(`%%writefile requirements.txt\n${reqs}`, 'code'),
      cell(trainPy, 'code'),
    ],
  }
  return JSON.stringify(nb, null, 1)
}
